export const SUBMISSIONS_TEST_DATA = [
  {
    id: 1,
    author: {},
    title: 'Vlašský orech',
    submissionState: 'ACTIVE',
    submissionType: 'FREEBIE',
    location: { latitude: 48.155633, longitude: 17.04505, altitude: 0 },
    description: '',
    photos: ['https://dummyimage.com/600x400/000/fff&text=Submission+image'],
    tags: ['nuts'],
  },
  {
    id: 2,
    author: {},
    title: 'Špenát',
    submissionState: 'ACTIVE',
    submissionType: 'FREEBIE',
    location: { latitude: 48.152633, longitude: 17.03505, altitude: 0 },
    description: '',
    photos: ['https://dummyimage.com/600x400/000/fff&text=Submission+image'],
    tags: ['veggies'],
  },
  {
    id: 3,
    author: {},
    title: 'Broskyňa',
    submissionState: 'ACTIVE',
    submissionType: 'FREEBIE',
    location: { latitude: 48.156633, longitude: 17.05505, altitude: 0 },
    description: '',
    photos: ['https://dummyimage.com/600x400/000/fff&text=Submission+image'],
    tags: ['fruits'],
  },
  {
    id: 4,
    author: {},
    title: 'Tymián',
    submissionState: 'ACTIVE',
    submissionType: 'FREEBIE',
    location: { latitude: 48.158633, longitude: 17.09505, altitude: 0 },
    description: '',
    photos: ['https://dummyimage.com/600x400/000/fff&text=Submission+image'],
    tags: ['herbs'],
  },
  {
    id: 5,
    author: {},
    title: 'Pečiarka poľná',
    submissionState: 'ACTIVE',
    submissionType: 'FREEBIE',
    location: { latitude: 48.159633, longitude: 17.01505, altitude: 0 },
    description: '',
    photos: ['https://dummyimage.com/600x400/000/fff&text=Submission+image'],
    tags: ['mushrooms'],
  },
]
